### ISSUE TITLE
Root privileges works, changing group doesn't?

### ISSUE THREAD

**Issue by solomongrundy6** [MarinX/keylogger#18] opened 2024-05-31 17:07 UTC
I've been using this for a project of mine and everything works as expected if I run it with sudo.  In another issue, you mentioned that adding your user to the groups 'input' and 'plugdev' would allow you to run without root privileges, but this doesn't seem to work for me, I always get the error "Must be run as root".  Is there something else to it that I'm not aware of?  The device I'm trying to access seems properly permissioned (has read/write enabled for group input, which I'm a member of).

**Comment by MarinX** [comment] 2024-06-04 08:43
Looks like the issue is [here](https://github.com/MarinX/keylogger/blob/master/keylogger.go#L38)

The better way would be to check if the os.Open fails and if it's a permission problem, check if the user is root and give a solution.

Let me fix that with a PR

**Comment by MarinX** [comment] 2024-06-04 08:54
pushed the fix with test, please check now and let me know.
Closing the issue.

**Closed by MarinX** 2024-06-04 08:54 UTC
